services:
  application:
    container_name: application
    build:
      context: .
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - 5173:5173
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - database

  webserver:
    image: nginx
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/app
      - ./external/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - application

  database:
    image: postgres
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - loader-pgdata:/var/lib/postgresql/data

volumes:
  loader-pgdata:
