name: Deploy

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    env:
      DIR: ${{ github.run_id }}

    steps:
      - uses: actions/checkout@v4
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          source: "."
          target: ${{ vars.PATH_TO_APP }}/$DIR

      - name: deploy app
        uses: appleboy/ssh-action@v1.0.3
        env:
          PATH_TO_APP: ${{ vars.PATH_TO_APP }}
          SERVER_NAME: ${{ secrets.SERVER_NAME }}
          APP_URL: ${{ vars.APP_URL }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DIR: $DIR
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          envs: PATH_TO_APP,SERVER_NAME,DIR
          script: |
            cd $PATH_TO_APP
            chmod -R guo+w storage
            chmod -R guo+w bootstrap/cache
            sh ./deploy.sh $SERVER_NAME $PATH_TO_APP $APP_URL $DB_PASSWORD
            mkdir $DIR
            cd $_
            pwd
