name: Deploy

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          source: "."
          target: ${{ vars.PATH_TO_APP }}

      - name: deploy app
        uses: appleboy/ssh-action@v1.0.3
        env:
          PATH_TO_APP: ${{ vars.PATH_TO_APP }}
          SERVER_NAME: ${{ secrets.SERVER_NAME }}
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          envs: PATH_TO_APP,SERVER_NAME
          script: cd $PATH_TO_APP && sh ./deploy.sh $SERVER_NAME $PATH_TO_APP
